apiVersion: v1
data:
  secretAccessKey: {{ .Values.awsSecret | b64enc }}
  accessKeyId: {{ .Values.keyID | b64enc }}
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
